import * as icons from "./icons.js";
import type { ComponentIcon } from "./icons.js";

const tokens: Record<string, ComponentIcon> = {
  IconUndo: icons.IconUndo,
  IconRedo: icons.IconRedo,
  IconZoomIn: icons.IconZoomIn,
  IconZoomOut: icons.IconZoomOut,
  IconFit: icons.IconFit,
  IconMoon: icons.IconMoon,
  IconSun: icons.IconSun,
  IconEye: icons.IconEye,
  IconEyeOff: icons.IconEyeOff,
  IconJson: icons.IconJson,
  IconContinuousPages: icons.IconContinuousPages,
  IconWorkflow: icons.IconWorkflow,
  IconExport: icons.IconExport,
  IconPrinter: icons.IconPrinter,
  IconDownload: icons.IconDownload,
  IconLogo: icons.IconLogo,
  IconPlus: icons.IconPlus,
  IconAtom: icons.IconAtom,
  IconBlocks: icons.IconBlocks,
  IconLayers: icons.IconLayers,
  IconImages: icons.IconImages,
  IconDiamond: icons.IconDiamond,
  IconInspect: icons.IconInspect,
  IconPalette: icons.IconPalette,
  IconPrintLayout: icons.IconPrintLayout,
  IconHeader: icons.IconHeader,
  IconFooter: icons.IconFooter,
  IconCode: icons.IconCode,
  IconSparkles: icons.IconSparkles,
  IconDatabase: icons.IconDatabase,
  IconAudit: icons.IconAudit,
  IconCopy: icons.IconCopy,
  IconPaste: icons.IconPaste,
  IconDuplicate: icons.IconDuplicate,
  IconArrowUp: icons.IconArrowUp,
  IconArrowDown: icons.IconArrowDown,
  IconLock: icons.IconLock,
  IconUnlock: icons.IconUnlock,
  IconTrash: icons.IconTrash,
  IconBold: icons.IconBold,
  IconItalic: icons.IconItalic,
  IconUnderline: icons.IconUnderline,
  IconStrikethrough: icons.IconStrikethrough,
  IconClearFormat: icons.IconClearFormat,
  IconUpload: icons.IconUpload,
  IconClose: icons.IconClose,
  IconGrip: icons.IconGrip,
  IconChevronDown: icons.IconChevronDown,
  IconChevronLeft: icons.IconChevronLeft,
  IconChevronRight: icons.IconChevronRight,
  IconDocument: icons.IconDocument,
  IconPanel: icons.IconPanel,
  IconColumns: icons.IconColumns,
  IconLink: icons.IconLink,
  IconSearch: icons.IconSearch,
  IconParent: icons.IconParent,
  IconMore: icons.IconMore,
  IconEdit: icons.IconEdit,
  IconSave: icons.IconSave,
  IconLibrary: icons.IconLibrary,
  IconFunction: icons.IconFunction,
  IconFileStack: icons.IconFileStack,
  IconHistory: icons.IconHistory,
  IconRotateCcw: icons.IconRotateCcw,
  IconLoader: icons.IconLoader,
  IconImport: icons.IconImport,
  IconBadgeDollar: icons.IconBadgeDollar,
  IconCalendar: icons.IconCalendar,
  IconPortrait: icons.IconPortrait,
  IconLandscape: icons.IconLandscape,
  IconGlobe: icons.IconGlobe,
  IconMonitor: icons.IconMonitor,
  IconTablet: icons.IconTablet,
  IconPhone: icons.IconPhone,
  IconExternalLink: icons.IconExternalLink,
};

export function resolveIcon(
  token: string | undefined,
): ComponentIcon | undefined {
  return token ? tokens[token] : undefined;
}
