<script lang="ts">
  import RegionView from './RegionView.svelte';
  import PrintChromeEditor from './PrintChromeEditor.svelte';
  import { getEditorContext } from './context.svelte.js';
  import { getPageDimensions } from '../core/presets.js';
  import { effectivePrintMargins, renderPrintTemplateDocument } from '../renderer/print-templates.js';
  import { renderPageNumber } from '../renderer/render.js';
  import { mmToPx } from '../shared/math.js';
  import { resolvePrintSection, resolveSectionTemplate } from '../core/print-sections.js';
  import type { Page } from '../core/types.js';

  interface Props {
    page: Page;
    index: number;
    zoom: number;
    blocked?: boolean;
    onpageelement?: (pageId: string, element: HTMLElement | null) => void;
  }

  let { page, index, zoom, blocked = false, onpageelement }: Props = $props();
  const editor = getEditorContext();
  const dims = $derived(getPageDimensions(page.size, page.orientation));
  const margins = $derived(effectivePrintMargins(editor.doc, page.margins));
  const active = $derived(editor.activePageIndex === index);
  const chromeLabelTransform = $derived(
    zoom === 1 ? undefined : `scale(${1 / Math.max(zoom, 0.75)})`,
  );
  const section = $derived(resolvePrintSection(editor.doc, index));
  const headerTemplate = $derived(resolveSectionTemplate(editor.doc, 'header', index));
  const footerTemplate = $derived(resolveSectionTemplate(editor.doc, 'footer', index));
  const dataContext = $derived({
    ...editor.getDataContext(),
    page: { number: index + 1, total: editor.doc.pages.length },
  });
  const showHeaderRegion = $derived(!!page.regions.header && (page.headerVariant !== 'first' || index === 0));
  const showFooterRegion = $derived(!!page.regions.footer && (page.footerVariant !== 'first' || index === 0));
  const headerParityClass = $derived(page.headerVariant === 'odd-even'
    ? ((index + 1) % 2 === 1 ? 'ex-region--odd' : 'ex-region--even')
    : '');
  const footerParityClass = $derived(page.footerVariant === 'odd-even'
    ? ((index + 1) % 2 === 1 ? 'ex-region--odd' : 'ex-region--even')
    : '');
  const pageNumberHtml = $derived(renderPageNumber(page, index, editor.doc.pages.length));

  function bindPage(element: HTMLElement) {
    onpageelement?.(page.id, element);
    return { destroy: () => onpageelement?.(page.id, null) };
  }

  function printChromeSource(position: 'header' | 'footer'): string {
    return renderPrintTemplateDocument(editor.doc, position, {
      pageIndex: index,
      totalPages: editor.doc.pages.length,
      pageLabel: page.label,
      date: editor.doc.meta.updatedAt.slice(0, 10),
      dataContext: editor.getDataContext(),
      resolveData: editor.isProvidedCapabilityEnabled('data.resolve') && editor.dataPreviewEnabled,
    });
  }

  function openChrome(
    event: MouseEvent | KeyboardEvent,
    position: 'header' | 'footer',
    editing = false,
  ): void {
    event.stopPropagation();
    editor.openPrintChrome(position, index, editing);
  }

  function commitChrome(position: 'header' | 'footer', html: string): void {
    const resolved = resolveSectionTemplate(editor.doc, position, index);
    editor.printEditing = false;
    editor.updatePrintVariantForPage(position, index, resolved.variant, html);
  }
</script>

<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
<section
  class="exs-page-shell"
  class:exs-page-shell--active={active}
  class:exs-page-shell--blocked={blocked}
  style:width={`${mmToPx(dims.width) * zoom}px`}
  style:height={`${mmToPx(dims.height) * zoom}px`}
  onclick={(event) => {
    event.stopPropagation();
    editor.activePageIndex = index;
  }}
  onmousedown={() => (editor.activePageIndex = index)}
>
  <div class="exs-page-shell__number">Page {index + 1}{page.flow?.autoGenerated ? ' · Auto' : ''}</div>
  <div
    class="exs-page ex-page"
    class:exs-page--active={active}
    data-page-id={page.id}
    data-page-index={index}
    style:width={`${dims.width}mm`}
    style:height={`${dims.height}mm`}
    style:padding={`${margins.top}mm ${margins.right}mm ${margins.bottom}mm ${margins.left}mm`}
    style:transform={zoom === 1 ? undefined : `scale(${zoom})`}
    use:bindPage
  >
    {#if page.regions.background}
      <RegionView region={page.regions.background} name="background" {dataContext} pageIndex={index} totalPages={editor.doc.pages.length} />
    {/if}
    <div
      class="exs-page__content-frame"
      style:top={`${margins.top}mm`}
      style:right={`${margins.right}mm`}
      style:bottom={`${margins.bottom}mm`}
      style:left={`${margins.left}mm`}
      aria-hidden="true"
    ></div>

    <div
      class="exs-page__word-zone exs-page__word-zone--header"
      class:exs-page__word-zone--editing={editor.rightTab === 'print' && editor.printPosition === 'header' && active}
      class:exs-page__word-zone--direct-editing={editor.printEditing && editor.printPosition === 'header' && active}
      class:exs-page__word-zone--print-active={editor.isPrintTabActive}
      style:left={`${margins.left}mm`}
      style:right={`${margins.right}mm`}
      style:height={`${margins.top}mm`}
      role="button"
      tabindex="0"
      title="Double-click to edit the page header"
      onclick={(event) => openChrome(event, 'header')}
      ondblclick={(event) => openChrome(event, 'header', true)}
      onkeydown={(event) => { if (event.key === 'Enter') openChrome(event, 'header'); }}
    >
      <span class="exs-page__word-zone-label" style:transform={chromeLabelTransform}>Header · {section.section.label}</span>
      {#if headerTemplate.sectionIndex > 0 && headerTemplate.section.header.linkedToPrevious}
        <span class="exs-page__linked-label" style:transform={chromeLabelTransform}>Same as previous</span>
      {/if}
      {#if editor.printEditing && active && editor.printPosition === 'header'}
        <PrintChromeEditor
          document={editor.doc}
          position="header"
          html={headerTemplate.html}
          title={`Header · ${section.section.label} · ${headerTemplate.variant}`}
          oncommit={(html) => commitChrome('header', html)}
          oncancel={() => (editor.printEditing = false)}
        />
      {:else if editor.doc.print.enabled && editor.doc.print.header.enabled}
        <iframe
          class="exs-page__print-chrome exs-page__print-chrome--header"
          title={`Page ${index + 1} PDF header preview`}
          srcdoc={printChromeSource('header')}
          style:height={`${editor.doc.print.header.height}mm`}
        ></iframe>
      {:else}
        <span class="exs-page__word-zone-empty">Add header</span>
      {/if}
    </div>

    <div class="ex-page-content exs-page__content">
      {#if showHeaderRegion && page.regions.header}
        <RegionView region={page.regions.header} name="header" variantClass={headerParityClass} {dataContext} pageIndex={index} totalPages={editor.doc.pages.length} />
      {/if}
      {#if page.pageNumbering?.position === 'header'}{@html pageNumberHtml}{/if}
      <RegionView region={page.regions.body} name="body" {dataContext} pageIndex={index} totalPages={editor.doc.pages.length} />
      {#if showFooterRegion && page.regions.footer}
        <RegionView region={page.regions.footer} name="footer" variantClass={footerParityClass} {dataContext} pageIndex={index} totalPages={editor.doc.pages.length} />
      {/if}
      {#if page.pageNumbering?.position === 'footer'}{@html pageNumberHtml}{/if}
    </div>

    <div
      class="exs-page__word-zone exs-page__word-zone--footer"
      class:exs-page__word-zone--editing={editor.rightTab === 'print' && editor.printPosition === 'footer' && active}
      class:exs-page__word-zone--direct-editing={editor.printEditing && editor.printPosition === 'footer' && active}
      class:exs-page__word-zone--print-active={editor.isPrintTabActive}
      style:left={`${margins.left}mm`}
      style:right={`${margins.right}mm`}
      style:height={`${margins.bottom}mm`}
      role="button"
      tabindex="0"
      title="Double-click to edit the page footer"
      onclick={(event) => openChrome(event, 'footer')}
      ondblclick={(event) => openChrome(event, 'footer', true)}
      onkeydown={(event) => { if (event.key === 'Enter') openChrome(event, 'footer'); }}
    >
      <span class="exs-page__word-zone-label" style:transform={chromeLabelTransform}>Footer · {section.section.label}</span>
      {#if footerTemplate.sectionIndex > 0 && footerTemplate.section.footer.linkedToPrevious}
        <span class="exs-page__linked-label" style:transform={chromeLabelTransform}>Same as previous</span>
      {/if}
      {#if editor.printEditing && active && editor.printPosition === 'footer'}
        <PrintChromeEditor
          document={editor.doc}
          position="footer"
          html={footerTemplate.html}
          title={`Footer · ${section.section.label} · ${footerTemplate.variant}`}
          oncommit={(html) => commitChrome('footer', html)}
          oncancel={() => (editor.printEditing = false)}
        />
      {:else if editor.doc.print.enabled && editor.doc.print.footer.enabled}
        <iframe
          class="exs-page__print-chrome exs-page__print-chrome--footer"
          title={`Page ${index + 1} PDF footer preview`}
          srcdoc={printChromeSource('footer')}
          style:height={`${editor.doc.print.footer.height}mm`}
        ></iframe>
      {:else}
        <span class="exs-page__word-zone-empty">Add footer</span>
      {/if}
    </div>
    {#if blocked}
      <div class="exs-page__overflow-badge">Block is taller than one page</div>
    {/if}
  </div>
</section>
