import { describe, expect, it } from 'vitest';
import {
  applyCommand,
  createDocument,
  createNode,
  createPage,
  flowFragmentCount,
  planCollapseFlowGroup,
  planPageFlow,
  type PageFlowMeasurement,
} from '../src/lib/core/index.js';

function applyPlan(doc: ReturnType<typeof createDocument>, measurements: PageFlowMeasurement[]) {
  const plan = planPageFlow(doc, measurements);
  plan.commands.forEach((command) => applyCommand(doc, command));
  return plan;
}

describe('automatic page flow', () => {
  it('moves overflowing top-level blocks onto a generated sheet', () => {
    const doc = createDocument();
    const page = doc.pages[0]!;
    page.regions.body.style = { display: 'flex', gap: '24px', padding: '18px' };
    const nodes = ['One', 'Two', 'Three'].map((content) => createNode('text', { content }));
    page.regions.body.children.push(...nodes);
    const plan = applyPlan(doc, [{
      pageId: page.id,
      bodyTop: 100,
      bodyBottom: 500,
      nodes: [
        { nodeId: nodes[0]!.id, top: 100, bottom: 250, height: 150 },
        { nodeId: nodes[1]!.id, top: 250, bottom: 430, height: 180 },
        { nodeId: nodes[2]!.id, top: 430, bottom: 620, height: 190 },
      ],
    }]);

    expect(plan.commands.map((command) => command.type)).toEqual(['page:add', 'component:move']);
    expect(doc.pages).toHaveLength(2);
    expect(doc.pages[1]!.flow?.autoGenerated).toBe(true);
    expect(doc.pages[1]!.regions.body.style).toEqual(page.regions.body.style);
    expect(doc.pages[1]!.regions.body.style).not.toBe(page.regions.body.style);
    expect(doc.pages[0]!.regions.body.children.map((node) => node.props.content)).toEqual(['One', 'Two']);
    expect(doc.pages[1]!.regions.body.children.map((node) => node.props.content)).toEqual(['Three']);
  });

  it('moves all trailing overflow blocks in their original order', () => {
    const doc = createDocument();
    const page = doc.pages[0]!;
    const nodes = ['A', 'B', 'C', 'D'].map((content) => createNode('text', { content }));
    page.regions.body.children.push(...nodes);
    applyPlan(doc, [{
      pageId: page.id,
      bodyTop: 0,
      bodyBottom: 250,
      nodes: nodes.map((node, index) => ({
        nodeId: node.id,
        top: index * 100,
        bottom: (index + 1) * 100,
        height: 100,
      })),
    }]);
    expect(doc.pages[1]!.regions.body.children.map((node) => node.props.content)).toEqual(['C', 'D']);
  });

  it('flags an indivisible first block instead of creating pages forever', () => {
    const doc = createDocument();
    const page = doc.pages[0]!;
    const node = createNode('image', { src: 'huge.png' });
    page.regions.body.children.push(node);
    const plan = planPageFlow(doc, [{
      pageId: page.id,
      bodyTop: 0,
      bodyBottom: 400,
      nodes: [{ nodeId: node.id, top: 0, bottom: 700, height: 700 }],
    }]);
    expect(plan.commands).toEqual([]);
    expect(plan.blockedPageIds).toEqual([page.id]);
  });

  it('pulls content backward when an earlier sheet has room', () => {
    const doc = createDocument();
    const first = doc.pages[0]!;
    const second = createPage({ label: 'Page 2' });
    second.flow = { autoGenerated: true };
    doc.pages.push(second);
    const firstNode = createNode('text', { content: 'First' });
    const secondNode = createNode('text', { content: 'Second' });
    first.regions.body.children.push(firstNode);
    second.regions.body.children.push(secondNode);
    applyPlan(doc, [
      {
        pageId: first.id,
        bodyTop: 0,
        bodyBottom: 500,
        nodes: [{ nodeId: firstNode.id, top: 0, bottom: 200, height: 200 }],
      },
      {
        pageId: second.id,
        bodyTop: 0,
        bodyBottom: 500,
        nodes: [{ nodeId: secondNode.id, top: 0, bottom: 100, height: 100 }],
      },
    ]);
    expect(first.regions.body.children.map((node) => node.props.content)).toEqual(['First', 'Second']);
    expect(second.regions.body.children).toEqual([]);
  });

  it('removes an empty generated sheet after backward reflow', () => {
    const doc = createDocument();
    const generated = createPage({ label: 'Page 2' });
    generated.flow = { autoGenerated: true };
    doc.pages.push(generated);
    applyPlan(doc, []);
    expect(doc.pages).toHaveLength(1);
  });

  it('does nothing in manual pagination mode', () => {
    const doc = createDocument();
    doc.pagination.mode = 'manual';
    const page = doc.pages[0]!;
    const node = createNode('text', { content: 'Overflow' });
    page.regions.body.children.push(node);
    const plan = planPageFlow(doc, [{
      pageId: page.id,
      bodyTop: 0,
      bodyBottom: 100,
      nodes: [{ nodeId: node.id, top: 0, bottom: 200, height: 200 }],
    }]);
    expect(plan).toEqual({ commands: [], blockedPageIds: [] });
  });

  it('fragments rich text at a measured line boundary', () => {
    const doc = createDocument();
    const page = doc.pages[0]!;
    const original = '<p>First paragraph.</p><p>Second paragraph.</p>';
    const node = createNode('text', { content: original });
    page.regions.body.children.push(node);

    const plan = applyPlan(doc, [{
      pageId: page.id,
      bodyTop: 0,
      bodyBottom: 400,
      nodes: [{
        nodeId: node.id,
        top: 0,
        bottom: 520,
        height: 520,
        split: {
          kind: 'text',
          headContent: '<p>First paragraph.</p>',
          tailContent: '<p>Second paragraph.</p>',
          linesBefore: 3,
          linesAfter: 3,
        },
      }],
    }]);

    expect(plan.commands.map((command) => command.type)).toEqual([
      'page:add',
      'component:update',
      'component:add',
    ]);
    const head = doc.pages[0]!.regions.body.children[0]!;
    const tail = doc.pages[1]!.regions.body.children[0]!;
    expect(head.props.content).toBe('<p>First paragraph.</p>');
    expect(tail.props.content).toBe('<p>Second paragraph.</p>');
    expect(head.flow).toMatchObject({ groupId: node.id, kind: 'text', continuation: false });
    expect(tail.flow).toMatchObject({ groupId: node.id, kind: 'text', continuation: true });
    expect(flowFragmentCount(doc)).toBe(2);
  });

  it('fragments tables by source row range', () => {
    const doc = createDocument();
    const page = doc.pages[0]!;
    const rows = Array.from({ length: 8 }, (_, index) => ({ item: `Row ${index + 1}` }));
    const node = createNode('table', { columns: [{ key: 'item' }], rows });
    page.regions.body.children.push(node);
    applyPlan(doc, [{
      pageId: page.id,
      bodyTop: 0,
      bodyBottom: 300,
      nodes: [{
        nodeId: node.id,
        top: 0,
        bottom: 480,
        height: 480,
        split: { kind: 'table', splitIndex: 5, rowCount: 8 },
      }],
    }]);

    expect(doc.pages[0]!.regions.body.children[0]!.flow?.tableRange).toEqual({ start: 0, end: 5 });
    expect(doc.pages[1]!.regions.body.children[0]!.flow?.tableRange).toEqual({ start: 5, end: 8 });
  });

  it('flows a vertical container between complete child blocks', () => {
    const doc = createDocument();
    const page = doc.pages[0]!;
    const intro = createNode('text', { content: 'Invoice details' });
    const table = createNode('table', { columns: [{ key: 'item' }], rows: [{ item: 'One' }] });
    const totals = createNode('text', { content: 'Totals' });
    const container = createNode('container', { direction: 'column' }, [intro, table, totals]);
    page.regions.body.children.push(container);

    applyPlan(doc, [{
      pageId: page.id,
      bodyTop: 0,
      bodyBottom: 400,
      nodes: [{
        nodeId: container.id,
        top: 0,
        bottom: 620,
        height: 620,
        split: { kind: 'container', targetNodeId: table.id },
      }],
    }]);

    const head = doc.pages[0]!.regions.body.children[0]!;
    const tail = doc.pages[1]!.regions.body.children[0]!;
    expect(head.children?.map((node) => node.props.content)).toEqual(['Invoice details']);
    expect(tail.children?.map((node) => node.type)).toEqual(['table', 'text']);
    expect(head.flow).toMatchObject({ groupId: container.id, kind: 'container', continuation: false });
    expect(tail.flow).toMatchObject({ groupId: container.id, kind: 'container', continuation: true });
    expect(flowFragmentCount(doc)).toBe(2);

    applyCommand(doc, {
      type: 'component:move',
      payload: { nodeId: tail.id, targetParentId: page.regions.body.id, targetIndex: 1 },
    });
    applyPlan(doc, []);
    const restored = page.regions.body.children[0]!;
    expect(page.regions.body.children).toHaveLength(1);
    expect(restored.children?.map((node) => node.type)).toEqual(['text', 'table', 'text']);
    expect(restored.flow).toBeUndefined();
    expect(flowFragmentCount(doc)).toBe(0);
  });

  it('splits a table through nested vertical container shells and collapses losslessly', () => {
    const doc = createDocument();
    const page = doc.pages[0]!;
    const rows = Array.from({ length: 8 }, (_, index) => ({ item: `Row ${index + 1}` }));
    const heading = createNode('text', { content: 'Line items' });
    const table = createNode('table', { columns: [{ key: 'item' }], rows });
    const totals = createNode('text', { content: 'Totals' });
    const inner = createNode('container', { direction: 'column' }, [heading, table, totals]);
    const outer = createNode('container', { direction: 'column' }, [inner]);
    page.regions.body.children.push(outer);

    applyPlan(doc, [{
      pageId: page.id,
      bodyTop: 0,
      bodyBottom: 400,
      nodes: [{
        nodeId: outer.id,
        top: 0,
        bottom: 720,
        height: 720,
        split: {
          kind: 'container',
          targetNodeId: table.id,
          targetSplit: { kind: 'table', splitIndex: 5, rowCount: 8 },
        },
      }],
    }]);

    const headOuter = doc.pages[0]!.regions.body.children[0]!;
    const tailOuter = doc.pages[1]!.regions.body.children[0]!;
    const headTable = headOuter.children?.[0]?.children?.find((node) => node.type === 'table');
    const tailTable = tailOuter.children?.[0]?.children?.find((node) => node.type === 'table');
    expect(headTable?.flow?.tableRange).toEqual({ start: 0, end: 5 });
    expect(tailTable?.flow?.tableRange).toEqual({ start: 5, end: 8 });
    expect(flowFragmentCount(doc)).toBe(2);

    const collapse = planCollapseFlowGroup(doc, headTable!.flow!.groupId);
    collapse.commands.forEach((command) => applyCommand(doc, command));
    const restoredOuter = doc.pages[0]!.regions.body.children[0]!;
    const restoredInner = restoredOuter.children?.[0];
    const restoredTable = restoredInner?.children?.find((node) => node.type === 'table');
    expect(collapse.rootId).toBe(outer.id);
    expect(restoredInner?.children?.map((node) => node.type)).toEqual(['text', 'table', 'text']);
    expect(restoredTable?.flow).toBeUndefined();
    expect(restoredTable?.props.rows).toEqual(rows);
    expect(doc.pages[1]!.regions.body.children).toHaveLength(0);
  });

  it('collapses text fragments losslessly before editing', () => {
    const doc = createDocument();
    const first = doc.pages[0]!;
    const second = createPage({ label: 'Page 2' });
    second.flow = { autoGenerated: true };
    doc.pages.push(second);
    const original = '<p>Alpha</p><p>Beta</p>';
    const head = createNode('text', { content: '<p>Alpha</p>' });
    const tail = createNode('text', { content: '<p>Beta</p>' });
    head.flow = { groupId: head.id, kind: 'text', continuation: false, originalContent: original };
    tail.flow = { groupId: head.id, kind: 'text', continuation: true, originalContent: original };
    first.regions.body.children.push(head);
    second.regions.body.children.push(tail);

    const collapse = planCollapseFlowGroup(doc, head.id);
    collapse.commands.forEach((command) => applyCommand(doc, command));

    expect(collapse.rootId).toBe(head.id);
    expect(first.regions.body.children[0]!.props.content).toBe(original);
    expect(first.regions.body.children[0]!.flow).toBeUndefined();
    expect(second.regions.body.children).toHaveLength(0);
  });

  it('honours keep-together, keep-with-next, and break-before rules', () => {
    const keptDoc = createDocument();
    const keptPage = keptDoc.pages[0]!;
    const kept = createNode('text', { content: 'Indivisible' });
    kept.pagination = { keepTogether: true };
    keptPage.regions.body.children.push(kept);
    const keptPlan = planPageFlow(keptDoc, [{
      pageId: keptPage.id,
      bodyTop: 0,
      bodyBottom: 200,
      nodes: [{
        nodeId: kept.id,
        top: 0,
        bottom: 300,
        height: 300,
        split: {
          kind: 'text',
          headContent: 'One',
          tailContent: 'Two',
          linesBefore: 2,
          linesAfter: 2,
        },
      }],
    }]);
    expect(keptPlan.commands).toEqual([]);
    expect(keptPlan.blockedPageIds).toEqual([keptPage.id]);

    const linkedDoc = createDocument();
    const linkedPage = linkedDoc.pages[0]!;
    const linked = ['Intro', 'Heading', 'Body'].map((content) => createNode('text', { content }));
    linked[1]!.pagination = { keepWithNext: true };
    linkedPage.regions.body.children.push(...linked);
    applyPlan(linkedDoc, [{
      pageId: linkedPage.id,
      bodyTop: 0,
      bodyBottom: 250,
      nodes: linked.map((entry, index) => ({
        nodeId: entry.id,
        top: index * 100,
        bottom: (index + 1) * 100,
        height: 100,
      })),
    }]);
    expect(linkedDoc.pages[0]!.regions.body.children.map((entry) => entry.props.content)).toEqual(['Intro']);
    expect(linkedDoc.pages[1]!.regions.body.children.map((entry) => entry.props.content)).toEqual(['Heading', 'Body']);

    const breakDoc = createDocument();
    const breakPage = breakDoc.pages[0]!;
    const before = createNode('text', { content: 'Before' });
    const after = createNode('text', { content: 'After' });
    after.pagination = { breakBefore: true };
    breakPage.regions.body.children.push(before, after);
    applyPlan(breakDoc, [{
      pageId: breakPage.id,
      bodyTop: 0,
      bodyBottom: 500,
      nodes: [
        { nodeId: before.id, top: 0, bottom: 100, height: 100 },
        { nodeId: after.id, top: 100, bottom: 200, height: 100 },
      ],
    }]);
    expect(breakDoc.pages[1]!.regions.body.children[0]!.props.content).toBe('After');
  });
});
