import type { Command } from './commands.js';
import { createPage } from './create.js';
import { planAdjacentFragmentMerge, splitFlowNode } from './flow-fragments.js';
import type {
  ComponentNode,
  ExemplaraDocument,
  Page,
} from './types.js';

export { flowFragmentCount, planCollapseFlowGroup } from './flow-fragments.js';
export type { CollapseFlowGroupPlan } from './flow-fragments.js';

export interface PageFlowTextSplitMeasurement {
  kind: 'text';
  headContent: string;
  tailContent: string;
  linesBefore: number;
  linesAfter: number;
}

export interface PageFlowTableSplitMeasurement {
  kind: 'table';
  /** Number of rendered rows that fit in this fragment. */
  splitIndex: number;
  /** Total rendered rows in the current fragment. */
  rowCount: number;
}

export type PageFlowLeafSplitMeasurement =
  | PageFlowTextSplitMeasurement
  | PageFlowTableSplitMeasurement;

export interface PageFlowContainerSplitMeasurement {
  kind: 'container';
  /** Nested child at which the container tree should be partitioned. */
  targetNodeId: string;
  /** Optional safe text/table split when the target itself crosses the page. */
  targetSplit?: PageFlowLeafSplitMeasurement;
}

export type PageFlowSplitMeasurement =
  | PageFlowLeafSplitMeasurement
  | PageFlowContainerSplitMeasurement;

export interface PageFlowNodeMeasurement {
  nodeId: string;
  top: number;
  bottom: number;
  height: number;
  /** Safe internal split proposed by the framework-neutral DOM adapter. */
  split?: PageFlowSplitMeasurement;
}

export interface PageFlowMeasurement {
  pageId: string;
  bodyTop: number;
  bodyBottom: number;
  nodes: PageFlowNodeMeasurement[];
}

export interface PageFlowPlan {
  commands: Command[];
  /** Pages containing a first block too tall to move or fragment safely. */
  blockedPageIds: string[];
}

const FLOW_TOLERANCE_PX = 2;

function generatedPageAfter(source: Page, pageNumber: number): Page {
  const page = createPage({
    label: `Page ${pageNumber}`,
    size: { ...source.size },
    orientation: source.orientation,
    margins: { ...source.margins },
    withBackground: !!source.regions.background,
  });
  if (source.regions.background?.style) {
    page.regions.background!.style = { ...source.regions.background.style };
  }
  if (source.regions.body.style) {
    page.regions.body.style = { ...source.regions.body.style };
  }
  page.flow = { autoGenerated: true };
  return page;
}

function bodyHeight(measurement: PageFlowMeasurement): number {
  return Math.max(0, measurement.bodyBottom - measurement.bodyTop);
}

function applyKeepWithNext(
  nodes: readonly ComponentNode[],
  measurements: readonly PageFlowNodeMeasurement[],
  overflowIndex: number,
  availableHeight: number,
): number {
  let index = overflowIndex;
  let groupHeight = measurements[index]?.height ?? 0;
  while (index > 0 && nodes[index - 1]?.pagination?.keepWithNext) {
    const candidateHeight = groupHeight + (measurements[index - 1]?.height ?? 0);
    if (candidateHeight > availableHeight - FLOW_TOLERANCE_PX) break;
    groupHeight = candidateHeight;
    index -= 1;
  }
  return index;
}

/**
 * Plan one stable pagination mutation from live canvas measurements.
 *
 * The DOM adapter proposes safe rich-text/table splits. The core owns all AST
 * fragmentation, generated pages, keep rules, backward flow, and recombination.
 * One operation per pass keeps reflow deterministic across UI frameworks.
 */
export function planPageFlow(
  doc: ExemplaraDocument,
  measurements: PageFlowMeasurement[],
): PageFlowPlan {
  if (doc.pagination.mode !== 'auto') return { commands: [], blockedPageIds: [] };

  const mergeCommands = planAdjacentFragmentMerge(doc);
  if (mergeCommands.length > 0) return { commands: mergeCommands, blockedPageIds: [] };

  const measured = new Map(measurements.map((entry) => [entry.pageId, entry]));
  const blockedPageIds: string[] = [];

  // First push or fragment overflowing content forward.
  for (const [pageIndex, page] of doc.pages.entries()) {
    const pageMeasurement = measured.get(page.id);
    const bodyNodes = page.regions.body.children;
    if (!pageMeasurement || pageMeasurement.nodes.length === 0) continue;

    const physicalOverflowIndex = pageMeasurement.nodes.findIndex(
      (node) => node.bottom > pageMeasurement.bodyBottom + FLOW_TOLERANCE_PX,
    );
    const breakBeforeIndex = bodyNodes.findIndex(
      (node, index) => index > 0 && node.pagination?.breakBefore === true,
    );
    let overflowIndex = physicalOverflowIndex;
    if (breakBeforeIndex !== -1 && (overflowIndex === -1 || breakBeforeIndex < overflowIndex)) {
      overflowIndex = breakBeforeIndex;
    }
    if (overflowIndex === -1) continue;

    const splitIsPhysical = overflowIndex === physicalOverflowIndex;
    overflowIndex = applyKeepWithNext(
      bodyNodes,
      pageMeasurement.nodes,
      overflowIndex,
      bodyHeight(pageMeasurement),
    );

    let nextPage = doc.pages[pageIndex + 1];
    const commands: Command[] = [];
    if (!nextPage?.flow?.autoGenerated) {
      nextPage = generatedPageAfter(page, pageIndex + 2);
      commands.push({ type: 'page:add', payload: { page: nextPage, index: pageIndex + 1 } });
    }

    const measuredNode = pageMeasurement.nodes[overflowIndex];
    const sourceNode = bodyNodes[overflowIndex];
    const proposedSplit = splitIsPhysical && overflowIndex === physicalOverflowIndex
      ? measuredNode?.split
      : undefined;
    const fragmentation = sourceNode && proposedSplit
      ? splitFlowNode(sourceNode, proposedSplit)
      : null;

    if (fragmentation && sourceNode) {
      commands.push({
        type: 'component:update',
        payload: { nodeId: sourceNode.id, changes: fragmentation.headChanges },
      });
      commands.push({
        type: 'component:add',
        payload: { parentId: nextPage.regions.body.id, index: 0, node: fragmentation.tail },
      });
      pageMeasurement.nodes.slice(overflowIndex + 1).forEach((node, targetIndex) => {
        commands.push({
          type: 'component:move',
          payload: {
            nodeId: node.nodeId,
            targetParentId: nextPage!.regions.body.id,
            targetIndex: targetIndex + 1,
          },
        });
      });
      return { commands, blockedPageIds };
    }

    if (overflowIndex === 0 && physicalOverflowIndex === 0) {
      blockedPageIds.push(page.id);
      // Do not retain a page created speculatively for an unbreakable block.
      continue;
    }

    pageMeasurement.nodes.slice(overflowIndex).forEach((node, targetIndex) => {
      commands.push({
        type: 'component:move',
        payload: {
          nodeId: node.nodeId,
          targetParentId: nextPage!.regions.body.id,
          targetIndex,
        },
      });
    });
    if (commands.length > 0) return { commands, blockedPageIds };
  }

  // Then pull one complete block/fragment backward when space becomes available.
  for (let pageIndex = 0; pageIndex < doc.pages.length - 1; pageIndex++) {
    const page = doc.pages[pageIndex]!;
    const nextPage = doc.pages[pageIndex + 1]!;
    if (!nextPage.flow?.autoGenerated || nextPage.regions.body.children.length === 0) continue;
    const currentMeasurement = measured.get(page.id);
    const nextMeasurement = measured.get(nextPage.id);
    const firstNext = nextMeasurement?.nodes[0];
    const firstNextNode = nextPage.regions.body.children[0];
    if (!currentMeasurement || !firstNext || !firstNextNode || firstNextNode.pagination?.breakBefore) continue;
    const usedBottom = currentMeasurement.nodes.at(-1)?.bottom ?? currentMeasurement.bodyTop;
    const freeSpace = currentMeasurement.bodyBottom - usedBottom;
    if (firstNext.height <= freeSpace - FLOW_TOLERANCE_PX) {
      return {
        commands: [{
          type: 'component:move',
          payload: {
            nodeId: firstNext.nodeId,
            targetParentId: page.regions.body.id,
            targetIndex: page.regions.body.children.length,
          },
        }],
        blockedPageIds,
      };
    }
  }

  // Finally remove one empty generated sheet.
  if (doc.pagination.removeEmptyPages) {
    for (let pageIndex = doc.pages.length - 1; pageIndex > 0; pageIndex--) {
      const page = doc.pages[pageIndex]!;
      if (page.flow?.autoGenerated && page.regions.body.children.length === 0) {
        return {
          commands: [{ type: 'page:remove', payload: { pageId: page.id } }],
          blockedPageIds,
        };
      }
    }
  }

  return { commands: [], blockedPageIds };
}
