import { iterateRegions } from '../core/tree.js';
import type {
  ComponentDefinition,
  ComponentNode,
  ExemplaraDocument,
  RegionName,
} from '../core/types.js';
import { nodeDisplayLabel } from './editor.js';

export type LayerTreeKind = 'document' | 'page' | 'region' | 'component' | 'slot';

export interface LayerTreeNode {
  id: string;
  kind: LayerTreeKind;
  label: string;
  children: LayerTreeNode[];
  pageIndex?: number;
  regionName?: RegionName;
  nodeId?: string;
  componentType?: string;
  slotName?: string;
  bindingCount?: number;
  hidden?: boolean;
  locked?: boolean;
  continuation?: boolean;
  autoGenerated?: boolean;
}

export type LayerDefinitionResolver = (
  componentType: string,
) => ComponentDefinition | undefined;

const REGION_LABELS: Record<RegionName, string> = {
  header: 'Header region',
  body: 'Body region',
  footer: 'Footer region',
  background: 'Background region',
};

function componentLayer(
  node: ComponentNode,
  pageIndex: number,
  definitionFor?: LayerDefinitionResolver,
): LayerTreeNode {
  const definition = definitionFor?.(node.type);
  const children = (node.children ?? []).map((child) =>
    componentLayer(child, pageIndex, definitionFor),
  );
  const slotNames = new Set([
    ...Object.keys(definition?.slots ?? {}),
    ...Object.keys(node.slots ?? {}),
  ]);

  for (const slotName of slotNames) {
    const slotChildren = node.slots?.[slotName] ?? [];
    children.push({
      id: `slot:${node.id}:${slotName}`,
      kind: 'slot',
      label: definition?.slots?.[slotName]?.label ?? slotName,
      slotName,
      pageIndex,
      children: slotChildren.map((child) => componentLayer(child, pageIndex, definitionFor)),
    });
  }

  return {
    id: `component:${node.id}`,
    kind: 'component',
    label: nodeDisplayLabel(node, definition, 32),
    nodeId: node.id,
    componentType: node.type,
    pageIndex,
    bindingCount: node.dataBindings?.length ?? 0,
    hidden: node.hidden,
    locked: node.locked,
    continuation: node.flow?.continuation,
    children,
  };
}

/** Build the complete authoring hierarchy used by outline/layer panels. */
export function buildDocumentLayerTree(
  doc: ExemplaraDocument,
  definitionFor?: LayerDefinitionResolver,
): LayerTreeNode {
  return {
    id: `document:${doc.id}`,
    kind: 'document',
    label: doc.name,
    children: doc.pages.map((page, pageIndex) => ({
      id: `page:${page.id}`,
      kind: 'page',
      label: `Page ${pageIndex + 1} · ${page.label}`,
      pageIndex,
      autoGenerated: page.flow?.autoGenerated,
      children: [...iterateRegions(page)].map(([regionName, region]) => ({
        id: `region:${region.id}`,
        kind: 'region',
        label: REGION_LABELS[regionName],
        regionName,
        pageIndex,
        children: region.children.map((node) =>
          componentLayer(node, pageIndex, definitionFor),
        ),
      })),
    })),
  };
}

export function countLayerTreeNodes(
  node: LayerTreeNode,
  kind?: LayerTreeKind,
): number {
  const own = kind === undefined || node.kind === kind ? 1 : 0;
  return own + node.children.reduce((total, child) => total + countLayerTreeNodes(child, kind), 0);
}

/** Return the outline path from the document root to a component node. */
export function findLayerTreePath(
  root: LayerTreeNode,
  nodeId: string,
): LayerTreeNode[] | null {
  if (root.nodeId === nodeId) return [root];
  for (const child of root.children) {
    const childPath = findLayerTreePath(child, nodeId);
    if (childPath) return [root, ...childPath];
  }
  return null;
}
