import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { createDocument } from 'exemplara-core';
import { EditorSession, createFullEditorPreset } from 'exemplara-core/editor';
import { render } from 'exemplara-core/renderer';
import { createDataBindingPlugin, createWebAuthoringPlugin, createTemplateAuthoringPlugin } from 'exemplara-plugins/core';
import * as pdf from 'exemplara-plugins/pdf';
const document = createDocument();
const editor = new EditorSession({ document, composition: createFullEditorPreset({ plugins: [createDataBindingPlugin(), createWebAuthoringPlugin(), createTemplateAuthoringPlugin()] }) });
const seen = [];
const stop = editor.stores.selectedNode.subscribe(node => seen.push(node?.id ?? null));
const node = editor.addComponent('text', editor.activePage.regions.body.id);
assert.deepEqual(seen, [null, node.id]);
stop();
assert.equal(editor.canUndo, true);
assert.equal(typeof render(editor.snapshot()).html, 'string');
assert.ok(Object.keys(pdf).length);
const require = createRequire(import.meta.url);
assert.throws(() => require.resolve('svelte'), { code: 'MODULE_NOT_FOUND' });
assert.throws(() => require.resolve('exemplara-svelte'), { code: 'MODULE_NOT_FOUND' });
editor.destroy();
console.log('Packed headless editor, plugins and PDF import passed without Svelte installed.');
