import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
import { createServer } from 'vite';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const playground = resolve(root, '../exemplara-playground');
const server = await createServer({ root: playground, configFile: resolve(playground, 'vite.config.ts'), server: { host: '127.0.0.1', port: 0 } });
await server.listen();
let browser;
try {
  browser = await chromium.launch({ executablePath: process.env.EXEMPLARA_CHROMIUM_PATH ?? '/usr/bin/google-chrome', args: ['--no-sandbox'] });
  const page = await browser.newPage();
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${server.resolvedUrls.local[0]}?fixture=session-portability`);
  await page.getByLabel('Document name', { exact: true }).fill('Retained document');
  await page.getByLabel('Document name', { exact: true }).press('Tab');
  await page.getByTitle('Drag onto the page or click to add “Text”').click();
  await page.locator('.exs-inspector').waitFor();
  const content = page.locator('.exs-inspector textarea').first();
  await content.fill('Portable content'); await content.press('Tab');
  await page.getByTitle('Zoom in', { exact: true }).click();
  await page.getByRole('navigation', { name: 'View', exact: true }).getByRole('button', { name: 'JSON', exact: true }).click();
  assert.equal(await page.locator('.exs-editor').count(), 0);
  assert.ok((await page.locator('pre').textContent()).includes('Portable content'));
  await page.getByRole('navigation', { name: 'View', exact: true }).getByRole('button', { name: 'Editor', exact: true }).click();
  assert.equal(await page.getByLabel('Document name', { exact: true }).inputValue(), 'Retained document');
  assert.equal(await page.getByTitle('Reset zoom to 100%').textContent(), '125%');
  assert.equal(await page.locator('.exs-node--selected').count(), 1);
  assert.equal(await page.locator('.exs-inspector textarea').first().inputValue(), 'Portable content');
  await page.getByTitle('Undo (Ctrl+Z)', { exact: true }).click();
  assert.notEqual(await page.locator('.exs-inspector textarea').first().inputValue(), 'Portable content');
  await page.getByTitle('Redo (Ctrl+Shift+Z)', { exact: true }).click();
  assert.equal(await page.locator('.exs-inspector textarea').first().inputValue(), 'Portable content');
  const leftResize = page.getByRole('slider', { name: 'Resize left editor sidebar', exact: true });
  await leftResize.press('ArrowRight');
  const retainedWidth = await leftResize.getAttribute('aria-valuenow');
  const paragraph = page.locator('details').filter({ has: page.locator('summary', { hasText: /^Paragraph$/ }) });
  await paragraph.locator('summary').click();
  assert.equal(await paragraph.evaluate(element => element.open), false);
  const views = page.getByRole('navigation', { name: 'View', exact: true });
  await views.getByRole('button', { name: 'JSON', exact: true }).click();
  await views.getByRole('button', { name: 'Editor', exact: true }).click();
  assert.equal(await leftResize.getAttribute('aria-valuenow'), retainedWidth);
  assert.equal(await paragraph.evaluate(element => element.open), false);
  const rightTabs = page.getByRole('navigation', { name: 'Right panels', exact: true });
  await rightTabs.getByRole('button', { name: 'Data', exact: true }).click();
  await page.getByRole('button', { name: 'Paste JSON', exact: true }).click();
  const paste = page.getByLabel('Paste a JSON object or list', { exact: false });
  await paste.fill('{"uncommitted":{"value":42}}');
  await views.getByRole('button', { name: 'JSON', exact: true }).click();
  await views.getByRole('button', { name: 'Editor', exact: true }).click();
  assert.equal(await paste.inputValue(), '{"uncommitted":{"value":42}}');
  await page.getByRole('button', { name: 'Add these fields', exact: true }).click();
  await page.getByRole('tab', { name: 'Edit structure', exact: true }).click();
  await page.getByRole('navigation', { name: 'Right panels', exact: true }).getByRole('button', { name: 'Selected', exact: true }).click();
  await page.locator('.exs-node--selected').dblclick();
  const richText = page.locator('.exs-richtext__surface');
  await richText.fill('Retained rich-text draft');
  // Synthetic navigation removes the view without focusing another element and committing via blur.
  await views.getByRole('button', { name: 'JSON', exact: true }).evaluate(element => element.click());
  await page.locator('.exs-editor').waitFor({ state: 'detached' });
  await views.getByRole('button', { name: 'Editor', exact: true }).click();
  assert.equal(await richText.textContent(), 'Retained rich-text draft');
  await richText.press('Control+Enter');
  assert.equal(await page.locator('.exs-inspector textarea').first().inputValue(), 'Retained rich-text draft');
  await page.getByRole('button', { name: /^Settings/ }).click();
  await page.getByRole('button', { name: 'Website mode', exact: true }).click();
  await page.locator('.exs-web-page').first().waitFor();
  await page.getByRole('button', { name: 'Print mode', exact: true }).click();
  await page.locator('.exs-page').first().waitFor();
  await page.getByRole('button', { name: 'Close settings', exact: true }).click();
  await page.getByRole('navigation', { name: 'Right panels', exact: true }).getByRole('button', { name: 'Theme', exact: true }).click();
  await page.getByRole('heading', { name: 'Whole page', exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log('Browser insertion, content editing, Inspector, view reattachment, selection, zoom, undo/redo private panels, sidebar widths, disclosures, JSON drafts, rich-text drafts and application feature replacement passed.');
} finally { await browser?.close(); await server.close(); }
